package net.benc.export.sql.model;

public enum FieldType {
	STRING, INTEGER, DOUBLE, LONG, DATE, BOOLEAN, BINARY, TIMESTAMPASINT, TIMESTAMPASLONG, TIMESTAMPASINTTOHUMANFORMAT, TIMESTAMPASLONGTOHUMANFORMAT;
}